export const TYPES = {
    GET_MASSAGES_REQUEST: "GET_MASSAGES_REQUEST",
    GET_MASSAGES_REQUEST_SUCCSES:"GET_MASSAGES_REQUEST_SUCCSES",
    GET_MASSAGES_REQUEST_ERROR:"GET_MASSAGES_REQUEST_ERROR",
}